# Generated by Django 2.2.6 on 2019-10-31 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
