# Generated by Django 2.2.6 on 2019-10-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regmodel',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('dob', models.DateField()),
                ('email', models.CharField(max_length=20)),
                ('pno', models.IntegerField(max_length=10)),
            ],
        ),
    ]
