# Generated by Django 2.2.6 on 2019-10-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regmodel',
            name='pno',
            field=models.IntegerField(),
        ),
    ]
