# Generated by Django 2.2.6 on 2019-10-21 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20191021_1255'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reg',
            new_name='regi',
        ),
    ]
