# Generated by Django 2.2.6 on 2019-10-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20191021_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('mobno', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('uname', models.CharField(max_length=10)),
                ('pwd', models.CharField(max_length=10)),
                ('cpwd', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='regi',
        ),
    ]
