# Generated by Django 2.2 on 2019-11-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_signin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signin',
            name='id',
        ),
        migrations.AlterField(
            model_name='signin',
            name='uname',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
