# Generated by Django 2.2 on 2019-11-25 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_auto_20191124_1058'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signin',
        ),
    ]
