# Generated by Django 2.2 on 2019-11-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signin',
            fields=[
                ('uname', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='login',
        ),
    ]
